import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "@radix-ui/themes/styles.css";
import "./globals.css";
import Navbar from "@/app/Navbar";
import {Theme} from "@radix-ui/themes";
import Providers from "@/app/auth/Provider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en" suppressHydrationWarning
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
        <body className="">
        <Providers>
            <Theme accentColor="cyan">
                <main>
                    <Navbar/>
                    <div className="p-12">
                        {children}
                    </div>
                </main>
            </Theme>
        </Providers>
        </body>
        </html>
    );
}
