import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "@radix-ui/themes/styles.css";
import "./globals.css";
import Navbar from "@/app/Navbar";
import {Container, Theme} from "@radix-ui/themes";
import Providers from "@/app/auth/Provider";
import React from "react";
import QueryClientProvider from "@/app/QueryClientProvider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en" suppressHydrationWarning
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
        <body className="">
        <QueryClientProvider>
            <Providers>
                <Theme accentColor="cyan">
                    <main>
                        <Navbar/>
                        <div className="py-16 px-4">
                            <Container>
                                {children}
                            </Container>
                        </div>
                    </main>
                </Theme>
            </Providers>
        </QueryClientProvider>
        </body>
        </html>
    );
}
